# Generated with GPT-4

TAGS = ["Marketing", "Alert", "Refund", "Secur", "Support", "Auto"]
COUNTRIES = ["France", "United-Kingdom", "Germany", "Ireland"]
CAMPAIGNS = [
    "Automated Marketing Alerts",
    "Refund Security Hub",
    "Smart Support Alerts",
    "Refund Guard",
    "Marketing Shield",
    "Instant Support Alert System",
    "Auto-Refund Secure Gateway",
    "The Security Refund Pathway",
    "Marketing Guardian Alerts",
    "Automatic Support Nexus",
    "Auto-Alert Marketing Solutions",
    "Secure Refund Support",
    "Quick Alert Security Campaign",
    "Auto-Refund Safety Net",
    "Support Shield Pro",
    "Marketing Intelligence Alerts",
    "The Refund Assurance Campaign",
    "AlertGuard: Automatic Refund & Security",
    "Secure Support System",
    "Marketing Refunds Simplified",
    "Quick Secure Support Alerts",
    "Refund Watchtower",
    "Auto-Guard Support Line",
    "Automatic Refund Defender",
    "Marketing Alert Fortress",
    "Secure Refund Network",
    "Support Radar Alert System",
    "Refund SafeAlert Pro",
    "Marketing Shield Alerts",
    "Automatic Secure Response System",
    "QuickShield Support Solutions",
    "Refund Safety System",
    "Marketing Safeguard Alerts",
    "Auto-Alert Refund Guardian",
    "Proactive Support Defense",
    "Refund Defense Hub",
    "Secure Marketing Assist",
    "Instant Refund Security",
    "Refund Safety Beacon",
    "AlertPro: Automatic Refund Support",
    "Marketing Security Framework",
    "Support Alert Fortress",
    "Secure Refund Beacon",
    "Marketing Protection Network",
    "Auto-Refund Security Suite",
    "Support Alert Network",
    "Refund SecureLine",
    "Marketing AlertGuard",
    "Support Alert Tracker",
    "Refund Security Protocol",
    "Bright Horizons Initiative",
    "Innovate & Elevate",
    "Momentum Wave",
    "The Visionary Shift",
    "Pathway to Progress",
    "Next-Level Synergy",
    "Rise & Thrive Campaign",
    "The Future Forward Drive",
    "Empowerment Odyssey",
    "Catalyst for Change Initiative"
]

PRODUCTS = [
    "Laptops and Desktops",
    "Software Licenses (e.g., productivity suites, antivirus)",
    "Cloud Storage Solutions",
    "Networking Equipment (routers, switches)",
    "Cybersecurity Services",
    "IT Consulting Services",
    "Custom-Built PCs",
    "Mobile Devices (smartphones, tablets)",
    "Managed IT Services",
    "Data Backup and Recovery Solutions",
    "Printers and Scanners",
    "Website and E-Commerce Development Services",
    "Point of Sale (POS) Systems",
    "Smart Home Devices (IoT products, smart locks, thermostats)",
    "Server and Hosting Solutions"
]