CREATE OR REPLACE TRANSIENT TABLE RAW.CUSTOMERS (
    CUSTOMER_ID NUMBER(12,0),
    FIRST_NAME VARCHAR(200),
    LAST_NAME VARCHAR(200),
    FULL_NAME VARCHAR(400),
    EMAIL VARCHAR(255),
    COUNTRY VARCHAR(400)
)
ENABLE_SCHEMA_EVOLUTION = FALSE;