USE DATABASE DBT_CORTEX;
CREATE SCHEMA semantic_model.definitions;
GRANT USAGE ON DATABASE semantic_model TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA semantic_model.definitions TO ROLE PUBLIC;

USE SCHEMA semantic_model.definitions;
CREATE STAGE dbt_app DIRECTORY = (ENABLE = TRUE);
GRANT READ ON STAGE DBT_CORTEX.DEFINITIONS.DBT_APP TO ROLE PUBLIC;