CREATE OR REPLACE USER KevinYamagata_bot
  PASSWORD = 'KevinYamagata_2046'
  DEFAULT_ROLE = ACCOUNTADMIN
  DEFAULT_WAREHOUSE = 'COMPUTE_WH'
  DEFAULT_NAMESPACE = 'SNOWFLAKE_SAMPLE_DATA.TPCH_SF10'
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE ACCOUNTADMIN TO USER KevinYamagata_bot;