USE DATABASE DBT_CORTEX;
CREATE SCHEMA IF NOT EXISTS DBT_CORTEX.DEFINITIONS;
GRANT USAGE ON SCHEMA DBT_CORTEX.DEFINITIONS TO ROLE PUBLIC;

USE SCHEMA DBT_CORTEX.DEFINITIONS;
CREATE OR REPLACE STAGE dbt_app DIRECTORY = (ENABLE = TRUE);
GRANT READ ON STAGE DBT_CORTEX.DEFINITIONS.DBT_APP TO ROLE PUBLIC;

CREATE OR REPLACE STAGE semantic_rpt_tag_campaigns_sends DIRECTORY = (ENABLE = TRUE);
GRANT READ ON STAGE DBT_CORTEX.DEFINITIONS.semantic_rpt_tag_campaigns_sends TO ROLE PUBLIC;