name: Generate DBT Docs
run-name: ${{ github.run_id }} generate docs
on: [push]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate documentation
        run: dbt docs generate