name: Generate DBT Docs
run-name: ${{ github.run_id }} generate docs
on: [push]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: install dbt-deps
        run: |
          cd dbt_app
          dbt deps

      - name: Write dbt profile to file
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.SNOWFLAKE_DBT_PROFILE }}" > ~/.dbt/profiles.yml

      - name: Generate documentation
        run: |
          cd dbt_app
          dbt docs generate

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v2
        with:
          name: dbt-docs
          path: dbt_app/target

  deploy-docs:
    runs-on: ubuntu-latest
    needs: generate-docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download documentation artifact
        uses: actions/download-artifact@v2
        with:
          name: dbt-docs
          path: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public