name: Generate DBT Docs
run-name: ${{ github.run_id }} generate docs
on: [push]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write dbt profile to file
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.SNOWFLAKE_DBT_PROFILE }}" > ~/.dbt/profiles.yml

      - name: Generate documentation
        run: |
          cd dbt_app
          dbt docs generate