name: Run DBT App
run-name: ${{ github.run_id }} run dbt app
on:
  push:
    branches:
      - main
    paths:
      - 'dbt_app/**'
jobs:
  run-dbt-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write dbt profile to file
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.SNOWFLAKE_DBT_PROFILE }}" > ~/.dbt/profiles.yml

      - name: setup dependencies
        run: |
          pip3 install -r requirements.txt

      - name: install dbt-deps
        run: |
          cd dbt_app
          dbt deps

      - name: debug dbt app
        run: |
          cd dbt_app
          echo "🚀 debug dbt app"
          dbt debug