name: Run DBT App
run-name: ${{ github.run_id }} run dbt app
on: [push]
jobs:
  run-dbt-app:
    runs-on: ubuntu-latest
    steps:
      - name: Echo first steps for runner
        run: echo "🚀 starts dbt app"
      - name: Write dbt profile to file
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILE }}" > ~/.dbt/profiles.yml