name: Run DBT App
run-name: ${{ github.run_id }} Deploy streamlit app and semantic models

on:
  push:
    branches:
      - main
    paths:
      - 'SiS/**'

jobs:
  deploy-semantic-models-and-streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python --version
          pip install -r requirements.txt

      - name: Setup Snow CLI connection #
        run: |
          snow connection add \
            --default \
            --silent \
            --connection-name DEMO_CORTEX_ACCOUNT_ADMIN \
            --account "{{ secrets.SNOWFLAKE_ACCOUNT }}" \
            --user "{{ secrets.SNOWFLAKE_USER }}" \
            --password "{{ secrets.SNOWFLAKE_PASSWORD }}"\
            --role "ACCOUNTADMIN" \
            --schema "PUBLIC" \
            --warehouse "COMPUTE_WH" \
            --database "DBT_CORTEX" \
            --authenticator "snowflake"


      - name: Deploy semantic models and Streamlit app
        run: |
          make upload-semantic-models
          make deploy-streamlit-app